version: '3.8'

services:
  contact-mgmt-db:
    image: postgres:17-alpine
    container_name: contact-mgmt-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network:
      - app-network
  
  contact-mgmt-backend:
    container_name: contact-mgmt-api
    image: contact-mgmt-api:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: contact-mgmt-db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      contact-mgmt-db:
        condition: healthy
  
  contact-mgmt-frontend:
    container_name: contact-mgmt-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - contact-mgmt-backend
    network:
      - app-network
  

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
